container:
  image: gradle:jdk8
  cpu: 4
  memory: 10G

test_task:
  auto_cancellation: false
  setup_workspace_script:
    - chmod +x ./gradlew
    - echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
    populate_script: ./gradlew setupDecompWorkspace
  wrapper_cache:
    folder: /home/gradle/.gradle/wrapper/dists/
    fingerprint_script: ls
  build_script:
    - ./gradlew build
  jar_artifacts:
    path: ./build/libs/**
  always:
    cleanup_before_cache_script:
      - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      - find ~/.gradle/caches/ -name "*.lock" -type f -delete
