test_task:
  auto_cancellation: true
  container:
    image: gradle:jdk8
    cpu: 8
    memory: 12G
  env:
    GH_TOKEN: ENCRYPTED[1e5598b3d4539404270fde8fb3bfb50045d8b5d4e58b73e542bd6b9906ed3644c220550820a872b599e9e945b06d47b7]
  setup_workspace_script: |
    chmod +x ./gradlew
    rm -rf $CIRRUS_WORKING_DIR/src/main/resources/build.txt
    echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
      cat settings.gradle
    populate_script: |
      ./gradlew setupDevWorkspace
  build_script: |
    ./gradlew test
    ./gradlew build
  jar_artifacts:
    path: ./build/libs/**
  upload_beta_build_link_script: |
    chmod -x ./gradlew
    git config --global user.email "support@rdil.rocks"
    git config --global user.name "RDIL Bot"
    if [ $CIRRUS_BRANCH == 'master' ]; then
      git pull
      git checkout master
      git remote rm origin
      rm -rf beta.txt
      echo 'https://api.cirrus-ci.com/v1/artifact/task/'${CIRRUS_BUILD_ID}'/jar/build/libs/Hyperium-2.0.jar' > beta.txt
      git add *.txt
      git commit -m "Added new beta link. [skip ci]"
      git remote add origin https://RDILBot:${GH_TOKEN}@github.com/RDIL/Hyperium-Jailbreak.git > /dev/null 2>&1
      git push --set-upstream origin master
    fi
  always:
    cleanup_before_cache_script: |
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
