task:
  auto_cancellation: true
  container:
    image: gradle:4.10-jdk
    cpu: 4
    memory: 12G
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      rm -rf ~/.gradle
    populate_script: gradle setupCiWorkspace
  matrix:
  - name: Cirrus CI
    script: gradle build
    jar_artifacts:
      path: ./build/libs/**
  always:
    cleanup_before_cache_script: |
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
