test_task:
  container:
    image: gradle:jdk8
  auto_cancellation: false
  setup_workspace_script:
    - echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
    - ./gradlew setupDecompWorkspace
  build_script:
    - ./gradlew build
