container:
  image: gradle:jdk8
  cpu: 4
  memory: 10G

test_task:
  auto_cancellation: true
  only_if: $CIRRUS_USER_PERMISSION != 'write'
  env:
    GH_TOKEN: ENCRYPTED[4a1baf42ed717adfab076e8cb95e45cd430ffedf6912da4997992073ca1b8695470d1e3cc962843bfc0bff3cd0303437]
  setup_workspace_script:
    - chmod +x ./gradlew
    - echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
    populate_script: ./gradlew setupDecompWorkspace
  build_script:
    - ./gradlew build
  jar_artifacts:
    path: ./build/libs/**
  always:
    cleanup_before_cache_script:
      - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      - find ~/.gradle/caches/ -name "*.lock" -type f -delete
  upload_link_script: |
    rm -rf beta.txt
    echo 'https://api.cirrus-ci.com/v1/artifact/task/'${CIRRUS_BUILD_ID}'/jar/build/libs/Hyperium-2.0.jar' > beta.txt
    git config --global user.email "support@rdil.rocks"
    git config --global user.name "RDIL Bot"
    git pull
    git checkout master
    git remote rm origin
    git add *.txt
    git commit -m "Added new beta link."
    if [ $CIRRUS_BRANCH == 'master' ]; then
      git remote add origin https://RDILBot:${GH_TOKEN}@github.com/RDIL/Hyperium-Jailbreak.git > /dev/null 2>&1
      git push --set-upstream origin master
    fi
