test_task:
  container:
    image: gradle:jdk8
  auto_cancellation: false
  setup_workspace_script:
    - chmod +x ./gradlew
    - echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script:
      - cat build.gradle
      - cat settings.gradle
      - cat gradle/wrapper/gradle-wrapper.properties
      - echo $OS
      - echo $CI
    populate_script: ./gradlew setupDecompWorkspace
  build_script:
    - ./gradlew build
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
